### ISSUE TITLE
Tooltip floats with scrollbar

### ISSUE THREAD

**Issue by Brisklemonade** [svelteuidev/svelteui-collections#3]
When hovering on a link in the header section, the Tooltip floats along the scroll bar's scroll position.

**Comment by Brisklemonade** [comment]
<img width="1700" alt="Screen Shot 2022-05-31 at 3 35 20 PM" src="https://user-images.githubusercontent.com/71530812/171279953-bd7ab94d-a9f5-427f-a749-154517f73827.png">

**Comment by ihsanmohamad** [comment]
I'm not sure how to fix, but I think I know how it happen. It's working fine until you click on 'Get Started' button and the page auto scroll to the 'all components' section.

**Comment by Brisklemonade** [comment]
Fixed in latest version of core
